apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/
        value: server
    target:
      group: apps
      kind: Deployment
      name: argo-server
      version: v1
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --auth-mode=server
    target:
      group: apps
      kind: Deployment
      name: argo-server
      version: v1
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --namespaced
    target:
      group: apps
      kind: Deployment
      name: argo-server
      version: v1
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value:  --loglevel=warn
    target:
      group: apps
      kind: Deployment
      name: argo-server
      version: v1
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --loglevel=warn
    target:
      group: apps
      kind: Deployment
      name: workflow-controller
      version: v1
resources:
  - github.com/argoproj/argo-workflows/manifests/namespace-install?ref=v3.4.5
