apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: "- op: add\n  path: /spec/template/spec/containers/0/args/-\n  value: --loglevel=warn\n
    \ "
  target:
    group: apps
    kind: Deployment
    name: argo-server
    version: v1
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --loglevel=warn
  target:
    group: apps
    kind: Deployment
    name: workflow-controller
    version: v1
resources:
- github.com/argoproj/argo-workflows/manifests/namespace-install?ref=v3.4.5
