apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: monitoredrepo-eventbus
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  nats:
    native:
      replicas: 3
      auth: token
      maxPayload: "2MB"
      containerTemplate:
        resources:
          limits:
            cpu: 500m
            memory: 4Gi
            ephemeral-storage: 2Gi
          requests:
            cpu: 200m
            memory: 1Gi
            ephemeral-storage: 2Gi
---
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  nats:
    native:
      # Optional, defaults to 3. If it is < 3, set it to 3, that is the minimal requirement.
      replicas: 3
      # Optional, authen strategy, "none" or "token", defaults to "none"
      auth: token
